version: "3.8"

services:
    # 500xx Microservices
    fetchdataservice:
        build:
            context: .
            dockerfile: src/fetchDataService/Dockerfile
        environment:
            FETCHDATAHOST: fetchdataservice
            PROMETHEUSHOST: prometheus
            PUSHGATEWAYHOST: pushgateway
        image: fetch_data_service
        networks:
            - southernOcean
        ports:
            - 50051:50051

    preparedataservice:
        build:
            context: .
            dockerfile: src/prepareDataService/Dockerfile
        environment: 
            PREPAREDATAHOST: preparedataservice
            PROMETHEUSHOST: prometheus
            PUSHGATEWAYHOST: pushgateway
        image: prepare_data_service
        networks: 
            - southernOcean
        ports: 
            - 50052:50052

    estimateservice:
        build:
            context: .
            dockerfile: src/estimateService/Dockerfile
        environment: 
            ESTIMATEHOST: estimateservice
            PROMETHEUSHOST: prometheus
            PUSHGATEWAYHOST: pushgateway
        image: estimate_service
        networks: 
            - southernOcean
        ports: 
            - 50053:50053

    # 501xx Aggregators
    powerestimationsp:
        build: 
            context: .
            dockerfile: src/powerEstimationSP/Dockerfile
        environment: 
            POWERESTIMATIONHOST: powerestimationsp
            FETCHHOST: fetchdataservice
            PREPAREHOST: preparedataservice
            ESTIMATEHOST: estimateservice
            PROMETHEUSHOST: prometheus
            PUSHGATEWAYHOST: pushgateway
        image: power_estimation_sp
        networks: 
            - southernOcean
        ports: 
            - 50101:50101

    # 502xx Gateways
    desktopgateway:
        build: 
            context: .
            dockerfile: src/desktopGateway/Dockerfile
        environment: 
            DESKTOPGATEWAYHOST: desktopgateway
            POWERESTIMATIONHOST: powerestimationsp
            PROMETHEUSHOST: prometheus
            PUSHGATEWAYHOST: pushgateway
        image: desktop_gateway
        networks: 
            - southernOcean
        ports: 
            - 50201:50201

    # Envoy proxy
    envoyproxy:
        build:
            context: .
            dockerfile: src/envoy/Dockerfile
        image: envoy_proxy
        ports: 
            - 8080:8080

    pushgateway:
        image: prom/pushgateway
        networks:
           - southernOcean
        ports:
            - 9091:9091

    prometheus:
        build:
            context: .
            dockerfile: src/prometheus/Dockerfile
        image: my_prometheus
        networks:
            - southernOcean
        ports:
          - 9090:9090
        command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

networks:
    southernOcean:
        