# Server
server:
  port: 
    myself: "50051"
  authentication:
    jwt:
      secretKey: "secret" # Make this something safer
      tokenDuration: 15 # Duration (in minutes) that the token is valid for
    accessLevel:
      name:
        fetchDataService: "/FetchData/FetchDataService"
      role:
        fetchDataService: ["admin"]