# Server
server:
  port: 
    myself: "50201"
  authentication:
    jwt:
      secretKey: "secret" # Make this something safer
      tokenDuration: 15 # Duration (in minutes) that the token is valid for
    accessLevel:
      name:
        powerEstimationSP: "/PowerEstimationServices/PowerEstimationSP"
      role:
        powerEstimationSP: 
          - "admin"

# Client
client:
  port:
    estimationSP: "50101"
    authenticationService: "50401"
  timeout:
    connection: 5
    call: 15
  authenticatedMethods:
    name:
      powerEstimationSP: "/PowerEstimationServicePackage/PowerEstimatorService"
    requiresAuthentication:
      powerEstimationSP: true