# Server
server:
  port: 
    myself: "50052"
  authentication:
    jwt:
      secretKey: "secret" # Make this something safer
      tokenDuration: 15 # Duration (in minutes) that the token is valid for
    accessLevel:
      name:
        prepareDataService: "/PrepareData/PrepareEstimateDataService"
      role:
        prepareDataService: ["admin"]