# Server
server:
  port: 
    myself: "50053"
  authentication:
    jwt:
      secretKey: "secret" # Make this something safer
      tokenDuration: 15 # Duration (in minutes) that the token is valid for
    accessLevel:
      name:
        estimateService: "/EstimatePower/EstimatePowerService"
      role:
        estimateService: ["admin"]